config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/create_donations'

  get 'dashboard/view_donations'

  get 'dashboard/order_entry'

  get 'dashboard/member'

  resources :addresses
  get 'dashboard/navigation_bar'

  get 'dashboard/about'

  get 'dashboard/contact'

  get 'dashboard/login'

  resources :donations
  root to: "dashboard#home"
  get 'dashboard/home'

  devise_for :users
  
  # Pages
#  get 'dashboard/about'
#  get 'dashboard/contact'
#  get 'dashboard/home'
#  get 'dashboard/login'
#  get 'dashboard/navigation_bar'
  
  get 'potato_controller/protocol1'

  get 'potato_controller/protocol2'

  get 'potato_controller/protocol3'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :zip_code, :phone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def create_donations
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:email, :produce, :quantity, :units, :data_entry_datetime, :pickup_date, :farmer_price, :picked_up, :dropped_off)
    end
end

app/controllers/potato_controller_controller.rb
class PotatoControllerController < ApplicationController
  def protocol1
  end

  def protocol2
  end

  def protocol3
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
    def bootstrap_version
        #use most recent version
        "4.0.0"
    end
end

app/helpers/potato_controller_helper.rb
module PotatoControllerHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_area :street, id: :address_street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_area :city, id: :address_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_area :state, id: :address_state %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.number_field :zip_code, id: :address_zip_code %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_area :phone, id: :address_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.zip_code %></td>
        <td><%= address.phone %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @address.zip_code %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @address.phone %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/dashboard/about.html.erb
<!--

About (informational) page.

-->
<div class="row">
    <div class="background col-md-12">
        <div class="logo">
            <img src="/assets/seed.png" />
        </div>
    </div>
</div>

<div class="row">
    <div class="header col-md-12">
            <h1>Our origins.</h1>
        </div>
    </div>
</div>

<div class="container-fluid" id="video-content">
    <div class="row">
        <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12"></div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="embed-responsive embed-responsive-16by9" id="ellen">
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/r7UB4S8IF9I"></iframe>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="embed-responsive embed-responsive-16by9" id="sfh">
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/HkjuEv6Wxcw"></iframe>
            </div>
        </div>
        <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12"></div>
    </div>
</div>

<style type="text/css">

    .about-content {
        margin-top: 1em;
    }
    
    .header h1 {
    }

    .background {
        padding-top: 25px;
        background-size: cover;
        background-position: center center;
        position: relative;
        height: 8vw;
        min-height: 150px;
        width: 100%;
    }
    .logo {
    }

        .logo > img {
            min-width: 250px;
            width: 27%;
            left: 50%;
            position: absolute;
            transform: translateX(-50%);
        }

    .header h1 {
        font-size: 4.15vw; /*control size of statement*/
        color: black;
        font-family: "Segoe UI Light";
        font-weight: 100;
        letter-spacing: -1px;
        text-align: center;
        opacity: 1;
        padding-bottom: 25px;
    }

    .video-content ellen{
        padding-bottom: 20px;
    }
    
    .video-content sfh{
        padding-top: 200px;
    }
</style>

app/views/dashboard/contact.html.erb
<!--

Contact information page.

-->
<!--
@{
    ViewData["Title"] = "Contact";
}

<h2>@ViewData["Title"]</h2>
-->
<div class="row">
    <div class="background col-md-12">
        <div class="logo">
            <img src="/assets/seed.png" />
        </div>
    </div>
</div>

<address>
    Cookeville<br />
    Tennessee 38506<br />
    P: 931.372.5555
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<style type="text/css">
    .about-content {
        margin-top: 1em;
    }

    h2 {
        text-align: center;
    }

    .background {
        background-size: cover;
        background-position: center center;
        position: relative;
        height: 8vw;
        min-height: 250px;
        width: 100%;
    }

    .logo {
    }

        .logo > img {
            min-width: 250px;
            width: 27%;
            left: 50%;
            position: absolute;
            transform: translateX(-50%);
        }

    address {
        font-size: 20px;
        color: black;
        font-family: "Segoe UI Light";
        font-weight: 100;
        letter-spacing: -1px;
        text-align: center;
        opacity: 1;
    }
</style>

app/views/dashboard/create_donations.html.erb
<h1>Dashboard#create_donations</h1>
<p>Find me in app/views/dashboard/create_donations.html.erb</p>

app/views/dashboard/home.html.erb
<!--

Home page.

-->
<body>

    <div class="row">
        <div class="background col-md-12">
            <div class="logo">
                <img src="/assets/seed.png" />
            </div>
            <div class="statement">
                <div class="ms">
                    <h3>Growing a healthy community,<br />one seed at a time.</h3>
                </div>
            </div>
        </div>

    </div>
    <div class="row form-group home-content">
        <div class="col-md-12" id="button-donor">
            <a href="/dashboard/member" class="btn btn-info" role="button" id="dbutton">Member Entry</a>
            <a href="/dashboard/order_entry" class="btn btn-info" role="button" id="pbutton">Order Entry</a>
            
        </div>
    </div>

    <div class="row form-group home-content">
        <div class="col-lg-4 col-md-4 col-sm-4"></div>
        <div class="col-lg-4 col-md-4 col-sm-4" id="NewsletterSignup">
            <input placeholder="News Letter Signup" class="form-control" id="newslettentry" type="text">
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4"></div>
    </div>


    <div class="row form-group home-content">
        <div class="col-md-12" id="button-signup">
            <input type="button" class="btn btn-warning" value="Signup" />
        </div>
    </div>
</body>

    <style type="text/css">
        .home-content {
            margin-top: 1em;
        }

        .background {
            background: url('/assets/background.jpg') no-repeat;
            background-size: cover;
            background-position: center center;
            position: relative;
            height: 33vw;
            min-height: 250px;
            width: 100%;
        }

        .logo {
        }

            .logo > img {
                min-width: 250px;
                width: 45%;
                left: 50%;
                position: absolute;
                transform: translateX(-50%);
            }

        .statement {
            background-color: rgba(0, 0, 0, 0.4);
            margin-left: -15px;
            margin-right: -15px;
            height: 14vw; /*height of black box*/
            min-height: 100px; /*scaling for mobile*/
            width: 100%;
            position: absolute;
            bottom: 0;
        }

        .ms h3 {
            font-size: 4.15vw; /*control size of statement*/
            color: white;
            font-family: "Segoe UI Light";
            font-weight: 100;
            letter-spacing: -1px;
            text-align: center;
            opacity: 1;
        }

        #button-donor {
            padding-top: 5px;
            text-align: center;
        }

        #dbutton {
            color: white;
            padding-right: 5px;
        }
        
        #pbutton {
            color: white;
        }

        #newslettentry {
            min-width: 100%;
            text-align: center;
        }

        #button-signup {
            padding-top: 5px;
            text-align: center;
        }
    </style>

app/views/dashboard/login.html.erb
<!--

Login page.

-->
<!--
@{
    ViewData["Title"] = "Login";
}
-->
<div class="row">
    <div class="background col-md-12">
        <div class="logo">
            <img src="/assets/seed.png" />
        </div>
    </div>
</div>

<div class="container">
    <div class="row" id="loginrow">
        <div class="col-sm" id="user">
            <input placeholder="Username" class="form-control" id="user" type="text">
        </div>
        <div class="col-sm" id="pass">
            <input placeholder="Password" class="form-control" id="pass" type="password">
        </div>
        <div class="col-sm" id="loginbutt">
            <input type="button" class="btn btn-warning" value="Login" />
        </div>
    </div>
</div>

<style type="text/css">
    .about-content {
        margin-top: 1em;
    }

    .background {
        background-size: cover;
        background-position: center center;
        position: relative;
        height: 8vw;
        min-height: 250px;
        width: 100%;
    }

    .logo {
    }

        .logo > img {
            padding-top: 30px;
            min-width: 250px;
            width: 27%;
            left: 50%;
            position: absolute;
            transform: translateX(-50%);
        }
    
    #loginrow {
    }

    #user {
        padding-left: 25%;
        padding-right: 25%;
        padding-top: 10px;
        text-align: center;
    }

    #pass {
        padding-left: 25%;
        padding-right: 25%;
        padding-top: 5px;
        padding-bottom: 5px;
        text-align: center;
    }

    #loginbutt {
        padding-left:47%;
    }
</style>

app/views/dashboard/member.html.erb
<!doctype html>
<form action="/action_page.php">
    <div class="row form-group home-content">
        <div class"col-md-12" id="ebase"></div>
    </div>
    
    <div class="row form-group home-content" id="e1">
        <div class="col-lg-4 col-md-2"></div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <input placeholder="First Name" class="form-control" id="fname" type="text" required>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <input placeholder="Last Name" class="form-control" id="lname" type="text" required>
        </div>
        <div class="col-lg-4 col-md-2"></div>
    </div>
    <div class="row form-group home-content" id="e2">
        <div class="col-lg-4 col-md-2"></div>
        <div class="col-lg-3 col-md-4 col-sm-12">
            <input placeholder="Street Address" class="form-control" id="add" type="text" required>
        </div>
        <div class="col-lg-1 col-md-4 col-sm-12">
            <input placeholder="Appt" class="form-control" id="addsec" type="text">
        </div>
        <div class="col-lg-4 col-md-2"></div>
    </div>
    <div class="row form-group home-content" id="e3">
        <div class="col-lg-4 col-md-2"></div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <input placeholder="City" class="form-control" id="city" type="text" required>
        </div>
        <div class="col-lg-1 col-md-2 col-sm-12">
            <input placeholder="ST" class="form-control" id="state" type="text" required>
        </div>
        <div class="col-lg-1 col-md-2 col-sm-12">
            <input placeholder="ZIP" class="form-control" id="zip" type="text" required>
        </div>
        <div class="col-lg-4 col-md-2"></div>
    </div>
    <div class="row form-group home-content" id="e4">
        <div class="col-md-4"></div>
        <div class="col-md-1">
            <input type="submit">
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-4"></div>
    </div>
</form>
<style type="text/css">
    
    ebase {
        background-color: black;
    }
    
    e1 {
    }
    
    e2 {
    }
    
    e3 {
        
    }
    
</style>

app/views/dashboard/navigation_bar.html.erb
<!--

Nav bar.

This page currently doesn't seem to be doing anything.

-->

<!DOCTYPE html>
<html>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
                <li><%= link_to "Home", dashboard_home_path %></li>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                  <li><%= link_to "About Seedfork", dashboard_about_path %></li>
                  <li><%= link_to "Contact Us", dashboard_contact_path %></li>
                  
                  <li><%= link_to "Submit Donation", dashboard_create_donations_path %></li>
                  <li><%= link_to "View Donations", dashboard_view_donations_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  
                    <li><%= link_to "Login", dashboard_login_path %></li>
                </ul>
            </div>
        </div>
    </nav>
</body>
</html>


<style type="text/css">
    #botlogo p {
       text-align: center;
    }
</style>

 <!-- 19
    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Seedfork</a>
21 -->

<!-- 24
    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
27 -->

<!-- 29
    <li><a asp-area="" asp-controller="Home" asp-action="Login">Login</a></li>
31 -->

app/views/dashboard/order_entry.html.erb
<h1>Dashboard#order_entry</h1>
<p>Find me in app/views/dashboard/order_entry.html.erb</p>

app/views/dashboard/view_donations.html.erb
<h1>Dashboard#view_donations</h1>
<p>Find me in app/views/dashboard/view_donations.html.erb</p>

app/views/donations/_form.html.erb
<%= form_with(model: donation, local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email, id: :donation_email %>
  </div>

  <div class="field">
    <%= form.label :produce %>
    <%= form.text_area :produce, id: :donation_produce %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_area :quantity, id: :donation_quantity %>
  </div>

  <div class="field">
    <%= form.label :units %>
    <%= form.text_area :units, id: :donation_units %>
  </div>

  <div class="field">
    <%= form.label :data_entry_datetime %>
    <%= form.datetime_select :data_entry_datetime, id: :donation_data_entry_datetime %>
  </div>

  <div class="field">
    <%= form.label :pickup_date %>
    <%= form.date_select :pickup_date, id: :donation_pickup_date %>
  </div>

  <div class="field">
    <%= form.label :farmer_price %>
    <%= form.text_field :farmer_price, id: :donation_farmer_price %>
  </div>

  <div class="field">
    <%= form.label :picked_up %>
    <%= form.check_box :picked_up, id: :donation_picked_up %>
  </div>

  <div class="field">
    <%= form.label :dropped_off %>
    <%= form.check_box :dropped_off, id: :donation_dropped_off %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Produce</th>
      <th>Quantity</th>
      <th>Units</th>
      <th>Data entry datetime</th>
      <th>Pickup date</th>
      <th>Farmer price</th>
      <th>Picked up</th>
      <th>Dropped off</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.email %></td>
        <td><%= donation.produce %></td>
        <td><%= donation.quantity %></td>
        <td><%= donation.units %></td>
        <td><%= donation.data_entry_datetime %></td>
        <td><%= donation.pickup_date %></td>
        <td><%= donation.farmer_price %></td>
        <td><%= donation.picked_up %></td>
        <td><%= donation.dropped_off %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @donation.email %>
</p>

<p>
  <strong>Produce:</strong>
  <%= @donation.produce %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @donation.quantity %>
</p>

<p>
  <strong>Units:</strong>
  <%= @donation.units %>
</p>

<p>
  <strong>Data entry datetime:</strong>
  <%= @donation.data_entry_datetime %>
</p>

<p>
  <strong>Pickup date:</strong>
  <%= @donation.pickup_date %>
</p>

<p>
  <strong>Farmer price:</strong>
  <%= @donation.farmer_price %>
</p>

<p>
  <strong>Picked up:</strong>
  <%= @donation.picked_up %>
</p>

<p>
  <strong>Dropped off:</strong>
  <%= @donation.dropped_off %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeedforkWebsite</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" id="test">
                </button> <a><%= link_to "Home", root_path, { :class => "navbar-brand"} %></a>
                </button> <a><%= link_to "About", dashboard_about_path, { :class => "navbar-brand"} %></a>
                </button> <a><%= link_to "Contact", dashboard_contact_path, { :class => "navbar-brand"} %></a
                </button> <a><%= link_to "Submit Donation (temp)", dashboard_create_donations_path, { :class => "navbar-brand"} %></a>
                </button> <a><%= link_to "View Donations (temp)", dashboard_view_donations_path, { :class => "navbar-brand"} %></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li><%= link_to "About Seedfork", dashboard_about_path %></li>
                  <li><%= link_to "Contact Us", dashboard_contact_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <!--
                    <li><a asp-area="" asp-controller="Home" asp-action="Login">Login</a></li>
                  -->
                    <li><%= link_to "Login", dashboard_login_path %></li>
                </ul>
            </div>
        </div>
    </nav>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
    <%= yield %>
  </body>
</html>

<style type="text/css">
  test {
    font.color: #808080;
  }
</style>

app/views/potato_controller/protocol1.html.erb
<h1>PotatoController#protocol1</h1>
<p>Find me in app/views/potato_controller/protocol1.html.erb</p>

app/views/potato_controller/protocol2.html.erb
<h1>PotatoController#protocol2</h1>
<p>Find me in app/views/potato_controller/protocol2.html.erb</p>

app/views/potato_controller/protocol3.html.erb
<h1>PotatoController#protocol3</h1>
<p>Find me in app/views/potato_controller/protocol3.html.erb</p>